# Generated by Django 4.1.4 on 2023-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Piece_Kg', models.CharField(max_length=30, null=True)),
                ('Type', models.CharField(max_length=30, null=True)),
                ('Quantity', models.CharField(max_length=30, null=True)),
                ('Price', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
