# Generated by Django 4.1.4 on 2023-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cash',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
