# Generated by Django 4.1.4 on 2023-02-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_remove_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='Quantity',
        ),
    ]
