# Generated by Django 4.1.4 on 2023-02-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_remove_stud_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='Quantity',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
